/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.23
 * Generated at: 2024-06-02 21:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.principal;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.ModelLogin;

public final class usuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1716939662041L));
    _jspx_dependants.put("jar:file:/C:/Users/conta/OneDrive/Área%20de%20Trabalho/JavaServletJDEV/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/curso-jsp/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602884772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("model.ModelLogin");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("  <!-- Pre-loader start -->\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "theme-loader.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- Pre-loader end -->\r\n");
      out.write("  <div id=\"pcoded\" class=\"pcoded\">\r\n");
      out.write("      <div class=\"pcoded-overlay-box\"></div>\r\n");
      out.write("      <div class=\"pcoded-container navbar-wrapper\">\r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"pcoded-main-container\">\r\n");
      out.write("              <div class=\"pcoded-wrapper\">\r\n");
      out.write("                  \r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navbarmainmenu.jsp", out, false);
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"pcoded-content\">\r\n");
      out.write("                      <!-- Page-header start -->\r\n");
      out.write("                       ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "page-header.jsp", out, false);
      out.write("\r\n");
      out.write("                      \r\n");
      out.write("                      <!-- Page-header end -->\r\n");
      out.write("                        <div class=\"pcoded-inner-content\">\r\n");
      out.write("                            <!-- Main-body start -->\r\n");
      out.write("                            <div class=\"main-body\">\r\n");
      out.write("                                <div class=\"page-wrapper\">\r\n");
      out.write("                                    <!-- Page-body start -->\r\n");
      out.write("                                    <div class=\"page-body\">\r\n");
      out.write("                                            <h3>Cadastro de usuario</h3>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-sm-12\">\r\n");
      out.write("												<!-- Basic Form Inputs card start -->\r\n");
      out.write("												<div class=\"card\">\r\n");
      out.write("\r\n");
      out.write("													<div class=\"card-block\">\r\n");
      out.write("\r\n");
      out.write("														<form enctype=\"multipart/form-data\" class=\"form-material\" action=\"");
      out.print( request.getContextPath() );
      out.write("/ServletUsuarioController\" method=\"post\" id=\"form-user\">\r\n");
      out.write("														\r\n");
      out.write("															<input type=\"hidden\" name=\"acao\" id=\"acao\" value=\"\">\r\n");
      out.write("														\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("                                                                <input type=\"text\" id=\"id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modelLogin.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\" required readonly>\r\n");
      out.write("                                                                <span class=\"form-bar\"></span>\r\n");
      out.write("                                                                <label class=\"float-label\">Id:</label>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            \r\n");
      out.write("                                                            <div class=\"form-group form-default input-group mb-4\">\r\n");
      out.write("                                                            	<div class=\"input-group-prepend\">\r\n");
      out.write("                                                            		<img alt=\"Image User\" src=\"\" width=\"70px\" id=\"fotoembase64\">\r\n");
      out.write("                                                    \r\n");
      out.write("                                                            	</div>\r\n");
      out.write("                                                            \r\n");
      out.write("                                                            	<input type=\"file\" accept=\"image/*\" name=\"filefoto\" onchange=\"visualizarImg('fotoembase64','filefoto');\" id=\"filefoto\" class=\"form-control-file\" style=\"margin-top: 15px; margin-left: 10px;\">\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("                                                                <input type=\"text\" id=\"nome\" name=\"nome\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modelLogin.nome}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control\" required>\r\n");
      out.write("                                                                <span class=\"form-bar\"></span>\r\n");
      out.write("                                                                <label class=\"float-label\">Nome:</label>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("\r\n");
      out.write("															\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("																<input type=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modelLogin.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"email\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">Email:\r\n");
      out.write("																	</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("																<select class=\"form-control form-select\" name=\"perfil\">\r\n");
      out.write("																	<option selected>[Selecione o perfil]</option>\r\n");
      out.write("																	<option value=\"ADMIN\" ");
 
																	
																	ModelLogin modelLogin = (ModelLogin) request.getAttribute("modelLogin");
																	
																	if (modelLogin != null && modelLogin.getPerfil().equals("ADMIN")) {
																		out.print(" ");
																		
																		out.print("selected");
																		
																		out.print(" ");
																		
																	}
      out.write("> ADMIN</option>\r\n");
      out.write("																	\r\n");
      out.write("																	<option value=\"SECRETARIA\" ");
 
																	
																	modelLogin = (ModelLogin) request.getAttribute("modelLogin");
																	
																	if (modelLogin != null && modelLogin.getPerfil().equals("SECRETARIA")) {
																		out.print(" ");
																		
																		out.print("selected");
																		
																		out.print(" ");
																		
																	}
      out.write(">SECRETARIA</option>\r\n");
      out.write("																	\r\n");
      out.write("																	<option value=\"AUXILIAR\" ");
 
																	
																		modelLogin = (ModelLogin) request.getAttribute("modelLogin");
																	
																		if (modelLogin != null && modelLogin.getPerfil().equals("AUXILIAR")) {
																		out.print(" ");
																		
																		out.print("selected");
																		
																		out.print(" ");
																		
																	}
      out.write(">AUXILIAR</option>\r\n");
      out.write("																</select>\r\n");
      out.write("															</div>\r\n");
      out.write("															\r\n");
      out.write("															\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("																<input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modelLogin.login}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"login\" id=\"login\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">Login:\r\n");
      out.write("																	</label>\r\n");
      out.write("															</div>\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("																<input type=\"password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modelLogin.senha}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"senha\" id=\"senha\"\r\n");
      out.write("																	class=\"form-control\" required=\"required\"> <span\r\n");
      out.write("																	class=\"form-bar\"></span> <label class=\"float-label\">Senha:</label>\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<div class=\"form-group form-primary form-static-label\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("																<div class=\"form-check\">\r\n");
      out.write("																	<input type=\"radio\" name=\"sexo\" checked value=\"MASCULINO\" ");
 
																		
																	modelLogin = (ModelLogin) request.getAttribute("modelLogin");
																	
																	if (modelLogin != null && modelLogin.getSexo().equals("MASCULINO")) {
																	out.print(" ");
																	
																	out.print("checked");
																	
																	out.print(" ");
																	}
																	
      out.write(">Masculino</>\r\n");
      out.write("																	\r\n");
      out.write("																	<input type=\"radio\" name=\"sexo\" value=\"FEMININO\" ");
 
																		
																	modelLogin = (ModelLogin) request.getAttribute("modelLogin");
																	
																	if (modelLogin != null && modelLogin.getSexo().equals("FEMININO")) {
																	out.print(" ");
																	
																	out.print("checked");
																	
																	out.print(" ");
																	}
																	
      out.write(" >Feminino</>\r\n");
      out.write("																	\r\n");
      out.write("																</div>\r\n");
      out.write("\r\n");
      out.write("															</div>\r\n");
      out.write("\r\n");
      out.write("															<button type=\"submit\" class=\"btn btn-success btn-round\">Salvar</button>\r\n");
      out.write("															<button type=\"button\" class=\"btn btn-danger btn-round\" onclick=\"criarDeleteComAjax()\">Excluir</button>\r\n");
      out.write("															<button type=\"button\" class=\"btn btn-primary btn-round\" onclick=\"limparForm()\">Limpar</button>\r\n");
      out.write("															<button type=\"button\" class=\"btn btn-secondary btn-round\"\r\n");
      out.write("																data-toggle=\"modal\" data-target=\"#exampleModal\">\r\n");
      out.write("																Pesquisar</button>\r\n");
      out.write("														</form>\r\n");
      out.write("\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("										\r\n");
      out.write("										<p id=\"mensagem\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("										<div style=\"height: 300px; overflow: scroll;\">\r\n");
      out.write("											<table class=\"table\" id=\"tabelaresultadosview\">\r\n");
      out.write("												<thead>\r\n");
      out.write("													<tr>\r\n");
      out.write("														<th scope=\"col\">ID</th>\r\n");
      out.write("														<th scope=\"col\">Nome</th>\r\n");
      out.write("														<th scope=\"col\">Ver</th>\r\n");
      out.write("\r\n");
      out.write("													</tr>\r\n");
      out.write("												</thead>\r\n");
      out.write("												<tbody>\r\n");
      out.write("													");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /principal/usuario.jsp(199,13) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/principal/usuario.jsp(199,13) '${modelLogins}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${modelLogins}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
        // /principal/usuario.jsp(199,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("ml");
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("														<tr>\r\n");
              out.write("															<td>");
              if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("</td>\r\n");
              out.write("															<td>");
              if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
                return;
              out.write("</td>\r\n");
              out.write("															<td><a class=\"btn btn-success\" href=\"");
              out.print( request.getContextPath() );
              out.write("/ServletUsuarioController?acao=buscarEditar&id=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">Ver</a></td>\r\n");
              out.write("														</tr>\r\n");
              out.write("													\r\n");
              out.write("													");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("												</tbody>\r\n");
      out.write("											</table>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("                                    <!-- Page-body end -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div id=\"styleSelector\"> </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Pesquisa de usuário</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"input-group mb-3\">\r\n");
      out.write("						<input type=\"text\" id=\"nomeBuscarModal\" class=\"form-control\"\r\n");
      out.write("							placeholder=\"Nome\"\r\n");
      out.write("							aria-label=\"Nome\" aria-describedby=\"basic-addon2\">\r\n");
      out.write("						<div class=\"input-group-append\">\r\n");
      out.write("							<button class=\"btn btn-primary\" type=\"button\" onclick=\"buscarUsuario()\">Buscar</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				<div style=\"height: 300px; overflow: scroll;\">\r\n");
      out.write("					<table class=\"table\" id=\"tabelaResultados\">\r\n");
      out.write("						<thead>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<th scope=\"col\">ID</th>\r\n");
      out.write("								<th scope=\"col\">Nome</th>\r\n");
      out.write("								<th scope=\"col\">Ver</th>\r\n");
      out.write("								\r\n");
      out.write("							</tr>\r\n");
      out.write("						</thead>\r\n");
      out.write("						<tbody>\r\n");
      out.write("							\r\n");
      out.write("						</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("					\r\n");
      out.write("				<span id=\"totalResultados\"></span>\r\n");
      out.write("					\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("				\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Fechar</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Required Jquery -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "javascriptFile.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	function verEditar(id){\r\n");
      out.write("		var urlAction = document.getElementById(\"form-user\").action;\r\n");
      out.write("\r\n");
      out.write("		window.location.href = urlAction + \"?acao=buscarEditar&id=\"+ id;\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function buscarUsuario(){\r\n");
      out.write("		\r\n");
      out.write("		var nomeBusca = document.getElementById(\"nomeBuscarModal\").value;\r\n");
      out.write("\r\n");
      out.write("		var urlAction = document.getElementById(\"form-user\").action;\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		if(nomeBusca != null && nomeBusca != \"\" && nomeBusca.trim() != \"\"){\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				method:\"get\",\r\n");
      out.write("				url: urlAction,\r\n");
      out.write("				data: \"nomeBusca=\"+nomeBusca + \"&acao=buscarUserAjax\",\r\n");
      out.write("				success: function(response) {\r\n");
      out.write("					\r\n");
      out.write("					var json = JSON.parse(response);\r\n");
      out.write("					\r\n");
      out.write("					$(\"#tabelaResultados > tbody > tr\").remove();\r\n");
      out.write("					\r\n");
      out.write("					for(var p = 0; p < json.length; p++) {\r\n");
      out.write("						$(\"#tabelaResultados > tbody\").append('<tr style=\"text-align: center;\"> <td>' + json[p].id + '</td> <td> ' + json[p].nome + '</td>  <td> <button type=\"button\" onclick=\"verEditar('+ json[p].id +')\" class=\"btn btn-info\">Ver</button> </td>  </tr>')\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					document.getElementById(\"totalResultados\").textContent = \"Resultados : \" + json.length;\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			}).fail(function(xhr, status, errorThrow){\r\n");
      out.write("				alert(\"Erro ao buscar usuario por Nome \" + xhr.responseText);\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function criarDeleteComAjax(){\r\n");
      out.write("		\r\n");
      out.write("		if(confirm(\"Deseja excluir os dados?\")) {\r\n");
      out.write("			var urlAction = document.getElementById(\"form-user\").action;\r\n");
      out.write("			var idUser = document.getElementById(\"id\").value;\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				\r\n");
      out.write("				method:\"get\",\r\n");
      out.write("				url: urlAction,\r\n");
      out.write("				data: \"id=\"+idUser + \"&acao=deletarAjax\",\r\n");
      out.write("				success: function(response) {\r\n");
      out.write("					limparForm();\r\n");
      out.write("					document.getElementById(\"mensagem\").textContent = response;\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			}).fail(function(xhr, status, errorThrow){\r\n");
      out.write("				alert(\"Erro ao deletar usuario por ID \" + xhr.responseText);\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function criarDelete(){\r\n");
      out.write("		if(confirm(\"Deseja excluir os dados?\")) {\r\n");
      out.write("			document.getElementById(\"form-user\").method = \"get\";\r\n");
      out.write("			document.getElementById(\"acao\").value = \"deletar\";\r\n");
      out.write("			document.getElementById(\"form-user\").submit();\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("		\r\n");
      out.write("	function limparForm(){\r\n");
      out.write("		var elementos = document.getElementById(\"form-user\").elements;\r\n");
      out.write("		console.log(elementos);\r\n");
      out.write("		\r\n");
      out.write("		for (p = 0; p < elementos.length; p++){\r\n");
      out.write("			elementos[p].value = \"\";\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function visualizarImg(fotoembase64, filefoto){\r\n");
      out.write("		\r\n");
      out.write("		var preview = document.getElementById(fotoembase64);\r\n");
      out.write("		console.log(preview)\r\n");
      out.write("		var fileUser = document.getElementById(filefoto).files[0];\r\n");
      out.write("		var reader = new FileReader();\r\n");
      out.write("		\r\n");
      out.write("		reader.onloadend = function (){\r\n");
      out.write("			preview.src = reader.result;\r\n");
      out.write("		\r\n");
      out.write("		};\r\n");
      out.write("		\r\n");
      out.write("		if(fileUser) {\r\n");
      out.write("			reader.readAsDataURL(fileUser);\r\n");
      out.write("		} else {\r\n");
      out.write("			preview.src = '';\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /principal/usuario.jsp(201,19) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.id}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /principal/usuario.jsp(202,19) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ml.nome}", java.lang.Object.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }
}
